personal_website/urls.py
from django.contrib import admin
from django.urls import path,include
from post import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('posts/', include('post.urls'), name="posts"),
    path('projects/', include('project.urls')),
    path('user/', include('user.urls')),
    # path('about/', views.about, name='about')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

post/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = "post"

urlpatterns = [
    path('', views.posts, name='posts'),
    path('makepost/', views.makepost, name="makepost"),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('post/<slug:slug>', views.post, name="post"),
    path('update/<int:id>', views.updatePost, name="updatePost"),
    path('delete/<int:id>', views.deletePost, name="deletePost"),
    path('tags/<slug:slug>', views.tag_posts, name="tagposts"),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.projects, name='projects'),
]

user/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = "user"

urlpatterns = [
    path('', views.user),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
]

post/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.urls import reverse

# Create your models here.

class Tag(models.Model):
    tag_name = models.CharField(max_length=10, blank=True, null=True)
    slug = models.SlugField(null=True, unique=True)

    def __str__(self):
        return self.tag_name

    def get_absolute_url(self):
        return reverse("post:tagposts", kwargs={'slug': self.slug})

class Post(models.Model):
    post_author = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    post_title = models.CharField(max_length=50)
    post_content = RichTextField()
    post_date = models.DateTimeField(auto_now_add=True)
    post_image = models.FileField(blank=True, null=True, verbose_name="Resim Ekle:")
    post_tags = models.ManyToManyField(Tag, verbose_name="Add Tag", blank=True)
    slug = models.SlugField(null=False, unique=True)

    def __str__(self):
        return self.post_title

    class Meta:
        ordering =['-post_date']

    def get_post_tag(self, i):
        return self.post_tags.all()[i]

    def get_absolute_url(self):
        return reverse("post:post", kwargs={'slug': self.slug})
    

project/models.py
from django.db import models
from ckeditor.fields import RichTextField
from post.models import Tag

class Project(models.Model):
    title = models.CharField(max_length=50)
    description = RichTextField()
    project_link = models.URLField()
    image = models.FileField(blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    tools = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return self.title
    

user/models.py
from django.db import models

# Create your models here.

post/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['post_title', 'post_content', 'post_image', 'post_tags', 'slug']

project/forms.py
from django import forms
from .models import Project

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'description', 'image', 'project_link']

user/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label = "Kullanıcı adı")
    password = forms.CharField(label = "Şifre", widget = forms.PasswordInput)

post/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm
from django.contrib import messages
from .models import Post, Tag
from django.contrib.auth.decorators import login_required
from user import urls

# Create your views here.

def index(request):
    posts = Post.objects.all()[:5]
    context = {
        "posts": posts,
    }
    return render(request, 'index.html', context)

"""
def about(request):
    return render(request, 'about.html')
""" 

def posts(request):
    posts = Post.objects.all()
    tags = Tag.objects.all()
    context = {
        "posts": posts,
        "tags": tags,
    }
    return render(request, 'posts.html', context)

def tag_posts(request, slug):
    posts = Post.objects.filter(post_tags__slug=slug)
    tag = Tag.objects.filter(slug=slug)[0]
    context = {
        'posts': posts,
        "tag": tag,
    }
    return render(request, 'posts.html', context)

def post(request, slug):
    post = get_object_or_404(Post, slug=slug)
    return render(request, 'post.html', {"post": post})

@login_required(login_url="user:login") 
def dashboard(request):
    posts = Post.objects.filter(post_author = request.user)
    context = {
        "posts": posts,
    }
    return render(request, 'dashboard.html', context)

@login_required(login_url="user:login") 
def makepost(request):
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.post_author = request.user
        post.save()
        messages.success(request, 'Yazı oluşturuldu.')
        return redirect('index')
    return render(request, 'makepost.html', {'form': form})

@login_required(login_url="user:login") 
def updatePost(request, id):
    post = get_object_or_404(Post, id=id)
    form = PostForm(request.POST or None, request.FILES or None, instance=post)
    if form.is_valid():
        post = form.save(commit=False)
        post.post_author = request.user
        if request.POST['post_tags']:
            post.post_tags.add(request.POST['post_tags'])
        post.save()
        return redirect("index")
    return render(request, 'update.html', {'form':form,})

@login_required(login_url="user:login") 
def deletePost(request, id):
    post = get_object_or_404(Post, id = id)
    post.delete()
    return redirect("post:dashboard")

project/views.py
from django.shortcuts import render
from .models import Project

def projects(request):
    projects = Project.objects.all()
    context = {
        'projects': projects,

    }
    return render(request, 'projects.html', context)

user/views.py
from django.shortcuts import render, redirect
from .forms import LoginForm
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required


# Create your views here.
def user(request):
    return redirect('login')

def loginUser(request):
    form = LoginForm(request.POST or None)
    context = {
        'form' : form,
    }
    if request.method == 'POST' and form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username = username, password = password)
        if user is None:
            messages.info(request, 'Kullanıcı bulunamadı')
            return render(request, 'login.html', context)
        messages.success(request, 'Giriş başarılı')
        login(request, user)
        return redirect('index')
    return render(request, "login.html", context)

@login_required(login_url="user:login") 
def logoutUser(request):
    logout(request)
    messages.success(request, 'Çıkış başarılı')
    return redirect('index')

templates/about.html
{% extends "layout.html" %}

{% block body %}

{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %} {% block body %}
<div class="row w-100">
  <div class="col-md-6 offset-md-3 align-self-center content-wrapper">
    <h4 class="mt-5">Yazılarım</h4>
    <table class="table table-sm">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Başlık</th>
          <th scope="col">Yayınlanma Tarih</th>
          <th scope="col">Seçenekler</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {% for post in posts %}
        <tr>
          <td>{{post.id}}</td>
          <td>
            <a href="{% url 'post:post' post.id %}" class="text-dark"
              >{{post.post_title}}</a
            >
          </td>
          <td>{{post.post_date}}</td>

          <td>
            <a
              class="btn btn-danger btn-sm"
              href="{% url 'post:updatePost' post.id %}"
              >Update</a
            >
          </td>
          <td>
            <a
              class="btn btn-danger btn-sm"
              href="{% url 'post:deletePost' post.id %}"
              >Delete</a
            >
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock body %}

templates/includes/navbar.html
<nav
  class="navbar fixed-top navbar-expand-md navbar-inverse border-bottom justify p-0"
>
  <a href="{% url 'index' %}" class="navbar-brand hoverable p-3"
    >AHMET ATAKAN SALAR</a
  >
  <button
    class="navbar-toggler navbar-toggler-right"
    type="button"
    data-toggle="collapse"
    data-target="#navbarCollapse"
    aria-controls="navbarCollapse"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span><i class="fas fa-bars mr-4"></i></span>
  </button>
  <div class="collapse navbar-collapse closed p-0" id="navbarCollapse">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item hoverable">
        <a class="nav-link" href="{% url 'post:posts'  %}">YAZILARIM</a>
      </li>
      <li class="nav-item hoverable">
        <a class="nav-link" href="{% url 'projects'  %}">PROJELERİM</a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item hoverable">
        <a class="nav-link" href="{% url 'post:dashboard'  %}">DASHBOARD</a>
      </li>
      <li class="nav-item hoverable">
        <a class="nav-link" href="{% url 'post:makepost'  %}">YAZI EKLE</a>
      </li>
      <li class="nav-item hoverable">
        <a class="nav-link" href="{% url 'user:logout'  %}">ÇIKIŞ</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

templates/includes/sidebar.html
<div class="sidebar">
    <ul class="list-group list-group-flush">
        <li class="list-group-item sidebar-item">
            <a href="{% url 'index'  %}" class="h3 text-dark">Ahmet Atakan Salar</a>
            <p class="mt-2 text-secondary">// Aspiring Developer</p>
        </li>
        <li class="list-group-item sidebar-item">
            <a href="/about" class="h6 text-dark">Hakkımda</a>
        </li>
        <li class="list-group-item sidebar-item">
            <a href="/posts" class="h6 text-dark">Yazılarım</a>
        </li>
        <li class="list-group-item sidebar-item">
            <a href="/portfolio"class="h6 text-dark">Portfolyo</a>
        </li>
        {% if request.user.is_authenticated %}
            <li class="list-group-item sidebar-item">
                <a href="/posts/dashboard/"class="h6 text-dark">Dashboard</a>
            </li>
            <li class="list-group-item sidebar-item">
                <a href="/posts/makepost/"class="h6 text-dark">Yazı Ekle</a>
            </li>
            <li class="list-group-item sidebar-item">
                <a href="/user/logout/"class="h6 text-dark">Çıkış Yap</a>
            </li>
        {% endif %}
        <li class="list-group-item sidebar-item">
            <a href="https://github.com/aatakansalar" class="text-secondary ml-1 mr-3"><i class="fab fa-github fa-lg"></i></a>
            <a href="https://twitter.com/AtakanSalar" class="text-secondary mr-3"><i class="fab fa-twitter fa-lg"></i></a>
            <a href="https://www.linkedin.com/in/ahmet-atakan-salar-7136881b1/" class="text-secondary mr-3"><i class="fab fa-linkedin-in fa-lg"></i></a>
        </li>
    </ul>
</div>

templates/index.html
{% extends "layout.html" %} {% load static %} {% block body %}
<div class="text-center" style="margin-top: 3.9rem">
  <div class="header-wrapper">
    <h1>
      <a href="/" class="text-decoration-none text-dark font-weight-bolder">Ahmet Atakan Salar</a>
    </h1>
    <h4 class="text-secondary pt-2">// Aspiring Developer</h4>
    <br />
    <a href="https://github.com/aatakansalar" target="_blank" title="github" class="text-dark mr-3"><i
        class="fab fa-github fa-2x"></i></a>
    <a href="https://twitter.com/AtakanSalar" target="_blank" title="twitter" class="text-dark mr-3"><i
        class="fab fa-twitter fa-2x"></i></a>
    <a href="https://www.linkedin.com/in/ahmet-atakan-salar-7136881b1/" target="_blank" title="linkedin"
      class="text-dark mr-3"><i class="fab fa-linkedin-in fa-2x"></i></a>
  </div>
</div>
<div class="row mb-5 pb-5">
  <div class="col-md-4 offset-md-3 align-self-center">
    <h3>Hakkımda</h3>
    <hr />
    <p>
      Ben Ahmet Atakan Salar, İstanbul Bilgi Üniversitesi Bilgisayar
      Mühendisliği 2. sınıf öğrencisiyim. Front-end ve back-end web
      geliştirmenin yanı sıra veri analizi, doğal dil işleme, makine öğrenmesi
      gibi konulara da ilgisi olan bir yazılımcı adayıyım. Bunların yanında
      resim, tarih ve world building gibi hobilerle uğraşıyorum.
    </p>
    <h3>Eğitim</h3>
    <hr />
    <ul>
      <li>
        İstanbul Bilgi Üniversitesi Bilgisayar Mühendisliği (Tam Burslu) (2018 -
        )
      </li>
      <li>Şehit Mustafa Serin Fen Lisesi (2014 - 2018)</li>
    </ul>
  </div>
  <div class="col-md-3">
    {% if posts %}
    <div class="posts">
      <h3>Son Yazılarım</h3>
      <hr />
      {% for post in posts %}
      <a href="{{ post.get_absolute_url }}" title="{{post.post_date}}"
        class="text-dark font-weight-bold">{{post.post_title}}</a>
      <br />
      {% endfor %}
      </ul>
      {% endif %}
    </div>
    <div class="mt-3">
      <br>
      <h3>İletişim</h3>
      <hr />
      <li style="list-style: none">
        <i class="fas fa-envelope fa-lg mr-2" title="e-mail"></i>
        <p class="tool-tag d-inline-flex"> a.atakansalar@gmail.com</p>
      </li>
    </div>
  </div>
</div>
{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>

    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'favicon.ico' %}"
    />

    <link rel="stylesheet" href="{% static 'style/style.css' %}" />
    <link rel="stylesheet" href="{% static 'style/snippet_style.css' %}" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.0.13/css/all.css"
      integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
      crossorigin="anonymous"
    />
    <title>Atakan Salar</title>
  </head>

  <body class="container-fluid">
    {% include "includes/navbar.html" %} {% block body %} {% endblock body %}

    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>

  <footer>
    <p class="text-center text-secondary pt-2 m-0">blr - atakansalar - 2020</p>
  </footer>
</html>

templates/login.html
{% extends "layout.html" %} {% load crispy_forms_tags %} {% block body %}
<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Giriş Yap</h3>
    <hr />
    <form method="POST">
      {% csrf_token %}
      <br />
      {{form|crispy}}
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>
{% endblock body %}

templates/makepost.html
{% extends "layout.html" %} {% load crispy_forms_tags %} {% block body %}
<div class="row w-100">
  <div class="col-md-6 offset-md-3 align-self-center content-wrapper">
    <h3>Post</h3>
    <hr />
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <br />
      {{ form.media }} {{form|crispy}} {{content | safe}}

      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>
{% endblock body %}

templates/post.html
{% extends "layout.html" %} {% block body %} {% if post %}
<div class="row m-3">
  <div class="col-md-8 offset-md-2 content-wrapper">
    <div class="post-wrapper">
      {% if post.post_image %}
      <img
        class="img-fluid"
        style="border-radius: 8px 8px 0 0"
        src="{{post.post_image.url}}"
        alt=""
      />
      {% endif %}
      <h2 class="mt-2">{{post.post_title}}</h2>
      <hr />
      <p>{{post.post_content|safe}}</p>
      <br />
      {% if post.post_tags.all %}
      <i class="fas fa-tags mr-2 text-dark"></i>
      {% for tag in post.post_tags.all %}
      <a
        href="{{ tag.get_absolute_url }}"
        class="mr-2 text-decoration-none badge badge-secondary badge-pill"
      >
        {{tag.tag_name}}
      </a>
      {% endfor %} {% endif %}
      <i class="float-right text-secondary">{{post.post_date}}</i>
      <h6 class="text-secondary text-right"></h6>
    </div>
  </div>
</div>
{% endif %} {% endblock body %}

templates/posts.html
{% extends "layout.html" %} {% block body %} {% if posts %}
<div class="row content-wrapper">
  <div class="col-md-6 offset-md-3">
    <div class="text-center">
      <h2 class="d-inline-flex mr-2 mt-5 pb-2 font-weight-bold">Yazılarım</h2>
      {% if tags %}
      <a
        href="#tags-collapse"
        data-toggle="collapse"
        title="etiketler"
        aria-expanded="true"
        class="show"
      >
        <i class="fas fa-tags text-dark fa-lg pt-4"></i>
      </a>
      <div class="collapse ml-3 show" id="tags-collapse">
        {% for tag in tags %}
        <a href="{{tag.get_absolute_url}}" class="badge badge-info badge-pill"
          >{{tag.tag_name}}</a
        >
        {% endfor %}
      </div>
      {% endif %}
      <hr class="mb-5" />
      {% if tag %}
      <p class="">
        <i class="fas fa-tags mr-2 text-dark"></i>Filtre Etiketi:
        <a href="{% url 'post:posts' %}" class="badge badge-info badge-pill"
          >{{tag.tag_name}} x</a
        >
      </p>
      {% endif %}
    </div>
    {% for post in posts %}
    <div class="card mb-5">
      {% if post.post_image %}
      <a href="{{ post.get_absolute_url }}" class="post-img"
        ><img
          class="card-img-top"
          src="{{post.post_image.url}}"
          alt="Card image cap"
      /></a>
      {% endif %}

      <div class="card-body">
        <a href="{{ post.get_absolute_url }}" class="text-dark"
          ><h4>{{post.post_title}}</h4></a
        >
        <small class="text-secondary">{{post.post_date}}</small>
        <p class="card-text">{{post.post_content|truncatewords:50|safe}}</p>
      </div>
      <div class="card-footer">
        {% if post.post_tags.all %}
        <i class="fas fa-tags mr-2 text-seconddary" title="Etiketler"></i>
        {% for tag in post.post_tags.all %}
        <a
          href="{{ tag.get_absolute_url }}"
          class="mr-2 text-decoration-none badge badge-info badge-pill"
          >{{tag.tag_name}}</a
        >
        {% endfor %} {% endif %}
        <a href="{{ post.get_absolute_url }}" class="w-100">
          <span class="badge badge-info float-right">Daha fazla ...</span>
        </a>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% else %}
<div class="row content-wrapper p-3" style="height: 400px">
  <div class="col-md-6 offset-md-3">
    <div class="text-center">
      <h2 class="d-inline-flex mr-2">Yazılarım</h2>
      {% if tag %}
      <p class="">
        <i class="fas fa-tags mr-2 text-dark"></i>Filtre Etiketi:
        <a href="{% url 'post:posts' %}" class="badge badge-info badge-pill"
          >{{tag.tag_name}} x</a
        >
      </p>
      {% endif %}
      <hr />
      <div class="alert-primary p-3 mt-4" style="border-radius: 8px">
        Bu etiketle yazı bulunamadı...
      </div>
    </div>
  </div>
</div>
{% endif %} {% endblock body %}

templates/projects.html
{% extends "layout.html" %} {% load static %} {% block body %}
<div style="margin: 8rem 3rem 15rem 3rem">
  {% for project in projects %}
  <div class="row text-center offset-md-2">
    <img
      class="img-fluid project-img col-md-5"
      src="/media/{{project.image}}"
      alt="{{project.title}}-image"
    />
    <div class="p-1 col-md-5 mt-5 mb-5 ml-md-5 pt-4">
      <h3 class=" d-inline-flex mr-1">{{project.title}}</h3>
        <a
          href="{{project.project_link|safe}}"
          target="_blank"
          title="Source Code"
          class="text-dark"
          ><i class="fas fa-link fa-lg"></i></a
          >
        {{project.description|safe}}
        <div class="text-center w-100 mt-4">
          {% for tool in project.tools.all %}
          <h4 class="d-inline-flex">
            <span class="badge badge-success tool-tag">{{tool.tag_name}}</span>
          </h4>
          {% endfor %}
        </div>
    </div>
  </div>
  <br>
  <hr />
  {% endfor %}
</div>
{% endblock body %}

templates/update.html
{% extends "layout.html" %} {% load crispy_forms_tags %} {% block body %}
<div class="row w-100">
  <div class="col-md-6 offset-md-3 align-self-center content-wrapper">
    <h3>Post</h3>
    <hr>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <br />
      {{ form.media }} {{form|crispy}} {{content | safe}}
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>
{% endblock body %}